import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

// https://vite.dev/config/
export default defineConfig({
  base: '/bfi-classroom/',
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 5174,
    strictPort: true,
    proxy: {
      // Direct /api calls (from production paths that don't include base)
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      // Media/uploads proxied from dev server to backend
      '/media': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      // /bfi-classroom/api calls (generated by BASE_URL + 'api/...' pattern in dev)
      '/bfi-classroom/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/bfi-classroom\/api/, '/api'),
      },
      // Media/uploads proxied from dev server to backend
      '/bfi-classroom/media': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/bfi-classroom\/media/, '/media'),
      },
      '/socket.io': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        ws: true,
      },
    },
  },
})
