import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'
import fs from 'fs'
import { lookup as mimeLookup } from 'mime-types'

// Vite plugin: in dev mode, serve files from ./uploads/ directly for /bfi-classroom/media/**
// This bypasses the http-proxy layer which silently returns 204 for binary file responses
// when a real browser (with sec-fetch-* headers + cookies) makes the request.
const serveUploadsPlugin = {
  name: 'serve-uploads-media',
  configureServer(server) {
    const uploadsDir = path.resolve('./uploads');
    server.middlewares.use('/bfi-classroom/media', (req, res, next) => {
      try {
        console.log(`[serveUploadsPlugin] HIT: req.url = ${req.url}`);
        let urlPath = req.url || '/';
        if (urlPath.split('?')[0].endsWith('/view')) {
          const parts = urlPath.split('?');
          parts[0] = parts[0].slice(0, -5);
          urlPath = parts.join('?');
        }
        // Strip query string and decode percent-encoded chars
        const relPath = decodeURIComponent(urlPath.split('?')[0]);
        const fullPath = path.resolve(uploadsDir, '.' + relPath);
        console.log(`[serveUploadsPlugin] fullPath = ${fullPath}`);

        // Security: no path traversal outside uploads dir
        if (!fullPath.startsWith(uploadsDir)) {
          console.log(`[serveUploadsPlugin] Path traversal check failed`);
          return next();
        }

        let stat;
        try { 
          stat = fs.statSync(fullPath); 
        } catch(e) { 
          console.log(`[serveUploadsPlugin] Stat failed: ${e.message}`);
          return next(); 
        }
        if (!stat.isFile()) {
          console.log(`[serveUploadsPlugin] Not a file`);
          return next();
        }

        const mimeType = mimeLookup(fullPath) || 'application/octet-stream';
        const inline = mimeType.startsWith('image/') || mimeType === 'application/pdf';

        res.setHeader('Content-Type', mimeType);
        res.setHeader('Content-Length', stat.size);
        res.setHeader('Content-Disposition', inline ? 'inline' : `attachment; filename="${path.basename(fullPath)}"`);
        res.setHeader('Cache-Control', 'public, max-age=0');
        res.setHeader('Cross-Origin-Resource-Policy', 'cross-origin');
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.statusCode = 200;
        fs.createReadStream(fullPath).pipe(res);
      } catch (err) {
        console.error(`[serveUploadsPlugin] ERROR:`, err);
        next();
      }
    });
  },
};

// https://vite.dev/config/
export default defineConfig({
  base: '/bfi-classroom/',
  plugins: [react(), serveUploadsPlugin],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      'es-toolkit/compat/last': path.resolve(__dirname, './src/compat-shims/last.js'),
      'es-toolkit/compat/sortBy': path.resolve(__dirname, './src/compat-shims/sortBy.js'),
      'es-toolkit/compat/uniqBy': path.resolve(__dirname, './src/compat-shims/uniqBy.js'),
      'es-toolkit/compat/throttle': path.resolve(__dirname, './src/compat-shims/throttle.js'),
      'es-toolkit/compat/maxBy': path.resolve(__dirname, './src/compat-shims/maxBy.js'),
      'es-toolkit/compat/minBy': path.resolve(__dirname, './src/compat-shims/minBy.js'),
      'es-toolkit/compat/range': path.resolve(__dirname, './src/compat-shims/range.js'),
      'es-toolkit/compat/sumBy': path.resolve(__dirname, './src/compat-shims/sumBy.js'),
      'es-toolkit/compat/get': path.resolve(__dirname, './src/compat-shims/get.js'),
      'es-toolkit/compat/omit': path.resolve(__dirname, './src/compat-shims/omit.js'),
      'es-toolkit/compat/isPlainObject': path.resolve(__dirname, './src/compat-shims/isPlainObject.js'),
    },
  },
  optimizeDeps: {
    include: ['recharts', 'es-toolkit'],
  },
  server: {
    port: 5174,
    proxy: {
      // Direct /api calls (from production paths that don't include base)
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      // Media/uploads proxied from dev server to backend
      '/media': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      // /bfi-classroom/api calls (generated by BASE_URL + 'api/...' pattern in dev)
      '/bfi-classroom/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/bfi-classroom\/api/, '/api'),
      },
      // NOTE: /bfi-classroom/media is intentionally NOT proxied here.
      // The serveUploadsPlugin (above) intercepts these requests and serves
      // files directly from ./uploads/ to avoid the 204 proxy issue.
      '/socket.io': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        ws: true,
      },
    },
  },
})
