import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

// https://vite.dev/config/
export default defineConfig({
  base: '/bfi-classroom/',
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      'es-toolkit/compat/last': path.resolve(__dirname, './src/compat-shims/last.js'),
      'es-toolkit/compat/sortBy': path.resolve(__dirname, './src/compat-shims/sortBy.js'),
      'es-toolkit/compat/uniqBy': path.resolve(__dirname, './src/compat-shims/uniqBy.js'),
      'es-toolkit/compat/throttle': path.resolve(__dirname, './src/compat-shims/throttle.js'),
      'es-toolkit/compat/maxBy': path.resolve(__dirname, './src/compat-shims/maxBy.js'),
      'es-toolkit/compat/minBy': path.resolve(__dirname, './src/compat-shims/minBy.js'),
      'es-toolkit/compat/range': path.resolve(__dirname, './src/compat-shims/range.js'),
      'es-toolkit/compat/sumBy': path.resolve(__dirname, './src/compat-shims/sumBy.js'),
      'es-toolkit/compat/get': path.resolve(__dirname, './src/compat-shims/get.js'),
      'es-toolkit/compat/omit': path.resolve(__dirname, './src/compat-shims/omit.js'),
      'es-toolkit/compat/isPlainObject': path.resolve(__dirname, './src/compat-shims/isPlainObject.js'),
    },
  },
  optimizeDeps: {
    include: ['recharts', 'es-toolkit'],
  },
  server: {
    port: 5174,
    strictPort: true,
    proxy: {
      // Direct /api calls (from production paths that don't include base)
      '/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      // Media/uploads proxied from dev server to backend
      '/media': {
        target: 'http://localhost:3001',
        changeOrigin: true,
      },
      // /bfi-classroom/api calls (generated by BASE_URL + 'api/...' pattern in dev)
      '/bfi-classroom/api': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/bfi-classroom\/api/, '/api'),
      },
      // Media/uploads proxied from dev server to backend
      '/bfi-classroom/media': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/bfi-classroom\/media/, '/media'),
      },
      '/socket.io': {
        target: 'http://localhost:3001',
        changeOrigin: true,
        ws: true,
      },
    },
  },
})
